### PR TITLE
Update prop-types require RN0.49

### PR DESCRIPTION
**Pull request by sonnn**
Update prop-types change for RN0.45-0.47

### CODE REVIEW

**Comment by MPiccinato** [comment]
@clauderic Could we get this merged?

**Comment by bmeverett** [comment]
Any update on this? Just ran into this today, and I would like to continue to use this package.

**Comment by BricePissard** [comment]
@clauderic could you accept the modification and merge it to the master branch.
When we use automatic commands such as 

```ssh
$> react-native install
```
or
```ssh
$> yarn install
```
it install back the latest release of each external module and we have to edit manually the file to correct this simple update.

**Comment by fungilation** [comment]
My solution has been `yarn add smartkarma/react-native-highlight-words`. No conflicts with global package upgrades.

But yes, if this repo is dead then we should move to an official fork. Like @sonnn's.

**Comment by clauderic** [comment]
Closing this in favour of #6

**Pull request closed without merging**
